const UPDATE_MOVIE_DATA_REQUEST = 'UPDATE_MOVIE_DATA_REQUEST';
const UPDATE_MOVIE_DATA_SUCCESS = 'UPDATE_MOVIE_DATA_SUCCESS';
const UPDATE_MOVIE_DATA_FAILURE = 'UPDATE_MOVIE_DATA_FAILURE';

const CONCAT_MOVIES = 'CONCAT_MOVIES';

const UPDATE_GENRES = 'UPDATE_GENRES';
const UPDATE_TYPE = 'UPDATE_TYPE';

export{
    UPDATE_MOVIE_DATA_FAILURE,
    UPDATE_MOVIE_DATA_REQUEST,
    UPDATE_MOVIE_DATA_SUCCESS,
    CONCAT_MOVIES,
    UPDATE_GENRES,
    UPDATE_TYPE
}